In [2]:
import numpy
import preprocessing
import _env

In [4]:
A = numpy.arange(6).reshape(3,2)
B = numpy.array([
    [1,1],
    [2,3],
    [4,5],
    [6,6]
])
print(A)
print(numpy.argmin(A,axis=0))
print(B)

[[0 1]
 [2 3]
 [4 5]]
[0 0]
[[1 1]
 [2 3]
 [4 5]
 [6 6]]


In [1]:
txt = "hello, my name is Peter, I am 26 years old"

x = txt.split(", ")

print(x) 

['hello', 'my name is Peter', 'I am 26 years old']


In [4]:
A = numpy.array([0,0,5,2,4,6])
print(numpy.argsort(A))
print(A[numpy.argsort(A)])

[0 1 3 4 2 5]
[0 0 2 4 5 6]


In [28]:
A = numpy.arange(30).reshape(3,2,5)
print(A.T.shape)

(5, 2, 3)


In [7]:
l = [0,4,2,3,5]
numpy.argpartition(
            l, -1)[-1:]

array([0, 2, 3, 1, 4], dtype=int64)