In [2]:
import numpy

In [2]:
def clip(values, vmin, vmax):
    values = numpy.where(values >= vmin, values, vmin)
    values = numpy.where(values >= vmax, vmax, values)
    return values

In [9]:
A = numpy.arange(10).reshape((2,5))
print(clip(A,2,5))
print(A)
print(numpy.sum(A),type(numpy.sum(A)))

[[2 2 2 3 4]
 [5 5 5 5 5]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
45 <class 'numpy.int32'>


In [15]:
x = numpy.arange(20).reshape(5, 4)
indices = numpy.indices((5, 4))
print(indices.shape)
print(x)
print(numpy.ndenumerate(x))

(2, 5, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [22]:
print(numpy.concatenate([numpy.expnumpy.where(x>=10)[0],numpy.where(x>=10)[1]],axis=-1))

[2 2 3 3 3 3 4 4 4 4 2 3 0 1 2 3 0 1 2 3]
